config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Generic syntax:
  # verb 'path', to: 'controller#action'
  root to: 'lists#index'
  resources :lists, except: [:edit, :update] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  # validates_uniqueness_of :movie_id, :scope   [:scope  :list_id]
  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie_id, scope: [:list_id]
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, uniqueness: true, presence: true
  # has_many :bookmarks, dependent: :destroy
  # has_many :movies, through: :bookmarks

  # include PgSearch::Model
  # pg_search_scope :search_by_name,
  # against: [ :name ],
  # using: {
  #   tsearch: { prefix: true }
    # <-- now `superman batm` will return something!

end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
  # belongs_to :movie
  # belongs_to :list
  # validates overview?
  # validates :title, uniqueness: true, presence: true
  # validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:new, :create]
  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to root_path
  end

  private

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def find_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to root_path
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Add a movie to your <%= @list.name %> list</h3>
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.input :comment, placeholder: 'Enter a comment about the movie' %>
          <%= f.association :movie, prompt: 'Select a movie' %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container p-5">
  <div class="row">
    <div class="col-3 pt-3 text-center">
      <p >Create a new list</p>
      <p class="btn btn-dark "><%= link_to 'New', new_list_path, class: "text-decoration-none text-info bg-dark" %></p>
      </div>

    <div class="col-12 p-4">
      <div class="container border border-dark text-center rounded pb-3">
        <p class=" badge bg-dark p-3 mt-5"style="width: 8rem;">ALL LISTS</p>
          <% @lists.each do |list| %>
          <div class="row">
            <div class="col-3 border border-dark bg-dark rounded text-center p-3 m-3">
              <%= link_to list_path(list), class: "text-decoration-none text-info bg-dark" do %>
              <p>Name : <%= list.name %></p>
              <p>Number of movies : <%= list.movies.count %></p>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container text-center pt-5">
  <div class="row ">
    <div class="col-12 col-md-6 offset-lg-3 bg-white rounded p-3 shadow">
      <h1 class="text-info bg-dark mb-5">Create new list</h1>
      <h2 class="text-info bg-dark mb-5">Here are the top rated movies :</h2>
    </div>
  </div>
  <div class="container py-5">
    <div class="row">
      <div class="col-12 col-md-6 offset-lg-3">
        <div class="bg-white rounded p-3 shadow">
          <h3 class="text-info bg-dark ">Create a new list</h3>
          <%= simple_form_for @list do |f| %>
            <%= f.input :name, placeholder: 'Drama' %>
            <%= f.submit class: 'btn btn-flat' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="container p-5">
  <div class="row">
    <div class="bg-white rounded p-3 shadow">
      <h2 class="m-3">Your <%= @list.name %> list has <%= pluralize(@list.movies.size, 'movie') %></h2>
      <div class="m-3 col">
        <% @list.bookmarks.each do |bookmark| %>
          <p class="col text-info">Title : <%= bookmark.movie.title %></p>
          <%= cl_image_tag("THE_IMAGE_ID_FROM_LIBRARY",width: 400, height: 300, crop: :fill) %>
          <!-- for face detection -->
          <%= cl_image_tag("IMAGE_WITH_FACE_ID",width: 150, height: 150, crop: :thumb, gravity: :face) %>
          <p class="col text-info">Your bookmark : <%= bookmark.comment %></p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-6 bg-dark text-info rounded p-3 shadow mt-3 d-flex justify-content-around">
      <%= link_to 'Back to all lists', lists_path, class: "text-decoration-none btn-flat text-info" %>
      <%= link_to 'Bookmark a movie', new_list_bookmark_path(@list), class: "text-decoration-none btn-flat text-info"%>
    </div>
  </div>
</div>